### PR TITLE
fix: compatible with Obsidian 1.2.0 version

### PR DESCRIPTION
**Pull request by bytemain**
this close: #102 

related: 
- https://github.com/FlorianWoelki/obsidian-icon-folder/pull/165

---

@aidenlx currently I cannot run this repo success. it seem you have some private package inside package.json
such as:
- @aidenlx/ts-config
- @aidenlx/prettier-config

and the dep is broken:
CleanShot 2023-03-31 at 14 04 03@2x

I delete the `yarn.lock` and it resolved, so I don't know if I should submit yarn.lock.

### CODE REVIEW

**Comment by Lisandra-dev** [comment]
Hello!
Little question : How do you build the main.js ? I have error on my side...

**Comment by bytemain** [comment]
> Hello! Little question : How do you build the main.js ? I have error on my side...

1. Remove these deps：
@aidenlx/ts-config
@aidenlx/prettier-config

replace tsconfig to:
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es6"
  },
  "include": ["src/**/*.ts"]
}

```

2. Delete the yarn.lock

**Comment by Lisandra-dev** [comment]
If I delete the yarn.lock, the yarn install refuse :'(

**Comment by bytemain** [comment]
[build.zip](https://github.com/aidenlx/alx-folder-note/files/11132167/build.zip)


For whom cannot build but want folder-note worked.

The code is not minified so you can check it to ensure it is safe.

**Comment by Lisandra-dev** [comment]
Work like a charm! Thank you :)

**Comment by namtrah** [comment]
This works for me as well. Thanks

**Comment by 7596ff** [comment]
thanks for the fix and the build.zip, i could not seem to build your branch from source.

**Comment by bytemain** [comment]
> thanks for the fix and the build.zip, i could not seem to build your branch from source.

The original code already had dependency issues. You can check the details in this PR's content to solve the problem.

**Pull request merged**
